msc_0=cn.qiany.basic.module.search.flow.processor.GeneraTextChainProcessor
msc_2=cn.qiany.basic.module.search.flow.processor.GeneralDecorateProcessor
msc_10=cn.qiany.basic.module.search.flow.processor.GeneralSearchSongProcessor