<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>cn.qiany.boot</groupId>
        <artifactId>qybasic</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>qybasic-module-search</artifactId>
    <packaging>jar</packaging>

    <name>qybasic-module-search</name>
    <description>
        音乐搜索模块
    </description>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <!-- Web 相关 -->
        <dependency>
            <groupId>cn.qiany.boot</groupId>
            <artifactId>qybasic-spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>cn.qiany.boot</groupId>
            <artifactId>qybasic-spring-boot-starter-security</artifactId>
        </dependency>

        <!-- 工具类相关 -->
        <dependency>
            <groupId>cn.qiany.boot</groupId>
            <artifactId>qybasic-spring-boot-starter-excel</artifactId>
        </dependency>

        <!-- DB 相关 -->
        <dependency>
            <groupId>cn.qiany.boot</groupId>
            <artifactId>qybasic-spring-boot-starter-mybatis</artifactId>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>3.8.1</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
